inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  Exclude:
    - Gemfile*
    - bin/*
    - gemfiles/**/*
    - test/**/*
    - vendor/bundle/**/*
  # https://github.com/rubocop/rubocop/issues/7771#issuecomment-628344513
  # Automatically enables new cops so that weaonly have to manually add them
  # if we are editing default behavior
  NewCops: enable

Rails:
  Enabled: true

# We don't care about method length, since we check method cyclomatic
# complexity.
Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - "devise-security.gemspec"
    - 'lib/devise-security.rb'

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/SymbolArray:
  EnforcedStyle: brackets

# Trailing commas make for clearer diffs because the last line won't appear
# to have been changed, as it would if it lacked a comma and had one added.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    # Using `[]` for string arrays instead of `()`, since normal arrays are
    # indicated with `[]` not `()`.
    '%w': '[]'
    '%W': '[]'

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  # They read better, more like normal English.
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

# Until we drop support for Rails 4.2, this can be different Rails 4.2 can work
# with ruby 2.2 and we don't know of any obvious problems with older versions of
# ruby, we just don't support them. Making the minimum ruby version match the
# oldest supported ruby will prevent people from installing the gem in older
# applications, which we don't want to do.
Gemspec/RequiredRubyVersion:
  Exclude:
    - 'devise-security.gemspec'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/devise-security/models/secure_validatable.rb'
